<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="SimpleCarMetamodel"
    nsURI="http://example.org/SimpleCarMetamodel"
    nsPrefix="simplecar">

  <eClassifiers xsi:type="ecore:EClass" name="Car">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="carId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manufacturer"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axes" upperBound="-1"
        eType="#//Axis" containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Axis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="axisId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wheels" upperBound="-1"
        eType="#//Wheel" containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Wheel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wheelId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pressure"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diameter"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
