<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pizza" nsURI="http://example.org/pizza" nsPrefix="pizza">
  <eClassifiers xsi:type="ecore:EClass" name="Food">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Restaurant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sells" upperBound="-1"
        eType="#//Food"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allFoods" ordered="false"
        upperBound="-1" eType="#//Food" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRestaurants" ordered="false"
        upperBound="-1" eType="#//Restaurant" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
