<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pizza" nsURI="http://example.org/pizza2" nsPrefix="pizza">
  <eClassifiers xsi:type="ecore:EEnum" name="FoodType">
    <eLiterals name="FOOD"/>
    <eLiterals name="DRINK" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Food" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//FoodType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Restaurant" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sells" upperBound="-1"
        eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allFoods" ordered="false"
        upperBound="-1" eType="#//Food" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allItems" ordered="false"
        upperBound="-1" eType="#//Item" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allRestaurants" ordered="false"
        upperBound="-1" eType="#//Restaurant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allPizzerias" ordered="false"
        upperBound="-1" eType="#//Pizzeria" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pizzeria" eSuperTypes="#//Restaurant"/>
</ecore:EPackage>
