/*
 * generated by Xtext 2.36.0
 */
package tools.vitruv.neojoin.ide;

import com.google.inject.Module;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.util.Modules2;
import org.jspecify.annotations.Nullable;
import tools.vitruv.neojoin.NeoJoinStandaloneSetup;

import static tools.vitruv.neojoin.utils.Assertions.check;

/**
 * NeoJoin language initialization for the Xtext language server.
 */
public class NeoJoinIdeSetup extends NeoJoinStandaloneSetup {

    public static EPackage.@Nullable Registry Registry = null;

    public NeoJoinIdeSetup() {
        super(getPackageRegistry());
    }

    @Override
    protected Module createModule() {
        return Modules2.mixin(super.createModule(), new NeoJoinIdeModule());
    }

    private static EPackage.Registry getPackageRegistry() {
        check(Registry != null, "Model registry not initialized");
        return Registry;
    }

}
