/*
 * generated by Xtext 2.36.0
 */
package tools.vitruv.neojoin.ide;

import org.eclipse.xtext.ide.editor.contentassist.IdeCrossrefProposalProvider;
import org.eclipse.xtext.ide.server.contentassist.ContentAssistService;
import org.eclipse.xtext.xbase.ide.contentassist.IIdeTypesProposalProvider;
import org.eclipse.xtext.xbase.typesystem.internal.IFeatureScopeTracker;
import tools.vitruv.neojoin.ide.custom.CustomClasspathBasedIdeTypesProposalProvider;
import tools.vitruv.neojoin.ide.custom.CustomContentAssistService;
import tools.vitruv.neojoin.ide.custom.CustomIdeCrossrefProposalProvider;
import tools.vitruv.neojoin.ide.custom.OptimizingFeatureScopeTrackerProvider2;

/**
 * Xtext service registry for the language server, see <a href="https://eclipse.dev/Xtext/documentation/302_configuration.html#dependency-injection">Xtext documentation</a>.
 */
@SuppressWarnings("unused")
public class NeoJoinIdeModule extends AbstractNeoJoinIdeModule {

    public Class<? extends ContentAssistService> bindContentAssistService() {
        return CustomContentAssistService.class;
    }

    public Class<? extends IdeCrossrefProposalProvider> bindIdeCrossrefProposalProvider() {
        return CustomIdeCrossrefProposalProvider.class;
    }

    @Override
    public Class<? extends IFeatureScopeTracker.Provider> bindIFeatureScopeTrackerProvider() {
        return OptimizingFeatureScopeTrackerProvider2.class;
    }

    @Override
    public Class<? extends IIdeTypesProposalProvider> bindIIdeTypesProposalProvider() {
        return CustomClasspathBasedIdeTypesProposalProvider.class;
    }

}
